all:
	g++ -g -o multiindexcontainer11 multiindexcontainer11.cpp
	g++ -g -o multiindexcontainer12 multiindexcontainer12.cpp
	g++ -g -o multiindexcontainer13 multiindexcontainer13.cpp

clean:
	rm multiindexcontainer11
	rm multiindexcontainer12
	rm multiindexcontainer13
