all:
	g++ -g -o multiindexcontainer1 multiindexcontainer1.cpp
	g++ -g -o multiindexcontainer2 multiindexcontainer2.cpp
	g++ -g -o multiindexcontainer3 multiindexcontainer3.cpp
	g++ -g -o multiindexcontainer4 multiindexcontainer4.cpp
	g++ -g -o multiindexcontainer5 multiindexcontainer5.cpp

clean:
	rm multiindexcontainer1
	rm multiindexcontainer2
	rm multiindexcontainer3
	rm multiindexcontainer4
	rm multiindexcontainer5
